### Post tweet
POST http://localhost:3000/tweet/post
Content-Type: application/json

{
    "content": "This is my tweet content"
}

### Delete tweet
DELETE http://localhost:3000/tweet/delete/{{id}}
Content-Type: application/json

### Get tweets by user id
GET http://localhost:3000/tweet/getByUser/{{id}}