name: Push to Docker Hub

on:
  push:
    branches:
      - master

jobs:
  # push_to_docker_hub:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v2

  #     - name: Login to Docker Hub
  #       uses: docker/login-action@v1
  #       with:
  #         username: ${{ secrets.DOCKERHUB_USERNAME }}
  #         password: ${{ secrets.DOCKERHUB_PASSWORD }}

  #     - name: Build and push Docker image
  #       uses: docker/build-push-action@v4
  #       with:
  #         context: .
  #         push: true
  #         tags: |
  #           marcbudd/linkup-service:${{ github.sha }}
  #           marcbudd/linkup-service:latest

  restart_docker_image:
    runs-on: ubuntu-latest
    # needs: push_to_docker_hub

    steps:
      - name: Execute remote ssh commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.PASSWORD }}
          script: |
            cd linkup-service
            kill $(lsof -t -i:3000)
            git pull
            npm install
            npm run build
            nohup go run main.go &
