name: Push to Docker Hub

on:
  push:
    branches:
      - master

jobs:
  push_to_docker_hub:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and tag Docker image
        run: |
          docker build -t dockerhub-marcbudd/linkup-service:latest .
          docker tag dockerhub-marcbudd/linkup-service:latest dockerhub-marcbudd/linkup-service:${{ github.sha }}

      - name: Push Docker image to Docker Hub
        run: |
          docker push dockerhub-marcbudd/linkup-service:latest
          docker push dockerhub-marcbudd/linkup-service:${{ github.sha }}
