name: Deployment

on:
  push:
    branches:
      - master

jobs:
  push_to_docker_hub:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            marcbudd/linkup-service:${{ github.sha }}
            marcbudd/linkup-service:latest

  restart_docker_image:
    runs-on: ubuntu-latest
    needs: push_to_docker_hub

    steps:
      - name: Execute remote ssh commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd linkup-service
            docker-compose pull
            docker-compose stop
            docker-compose rm -f
            docker-compose up -d
